### ISSUE TITLE
Cors policy

### ISSUE THREAD

**Issue by Brazilianian** [MClarkDev/ArylicJS#1]
Hello, i found your report about cors policy problem on forum - https://forum.arylic.com/t/adding-cors-headers-for-http-api/1584

I have the same now 

Have you found out the solution?

**Comment by MClarkDev** [comment]
Unfortunately I never got an answer to the question as you can see on the forum.
They way I call my devices now, I just ignore the CORS header.

I am going to close the issue as this is not something I can fix on my side.
